---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 1:32 PM
---

-----------------------------------------------------------------------------
-- 组装请求里面的各个产品线和每个产品线请求参数中携带的data数据
-- request请求里面请求数据里面的response->data里面可能有多个数组，
-- 每个数组代表对某个业务线的请求，这里将其产品名称、所需参数组合好，以便于在后面通过capture_multi并行调用
--
-----------------------------------------------------------------------------

module(..., package.seeall)

-----------------------------------------------------------------------------
-- 从传参里的各项数据中获取当前请求的产品线信息，以及每个产品线请求所需携带的参数
-- Input
-- @param core 调用者自身self对象
-- Returns
-- @return product_params 产品线和对应的data参数信息
-- @return ex_product 存在的产品线
-----------------------------------------------------------------------------
function get_product(core)
   ngx.say('获取产品名字等关键参数')
    return {},{ad='ad'}
end

-----------------------------------------------------------------------------
-- 获取设备类型
-- Input
-- @param core 调用者自身self
-- Returns
-- @return string 'pc'或者'mobile'
-----------------------------------------------------------------------------
function get_device_type(core)
    if core.from == 'pc' then
        return 'pc'
    end
    return 'mobile'
end

-----------------------------------------------------------------------------
-- 判断table中是否含有value值
-- Input
-- @param tables 包含数据的table
-- @param value 要判断的value
-- Returns
-- @return boolean ture或者false
-----------------------------------------------------------------------------
function is_in_table(tables, value)
    for _, v in pairs(tables) do
        if v == value then
            return true
        end
    end
    return false
end