---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 11:41 AM
---

module(..., package.seeall)
-- nginx 配置的全局变量
IDC = os.getenv('ENV_DATACENTER') -- 暂停使用，同时需保留
bx = {}
