---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 1:28 PM
---
-----------------------------------------------------------------------------
-- trends init的默认方法
-- 给传入的self对象增加多个字段，每个字段里面包含request请求的参数
-----------------------------------------------------------------------------
module(..., package.seeall)

-----------------------------------------------------------------------------
-- 执行方法
-- 封装request里面常用的数据以提供给后面的请求处理文件使用
-- 根据request里面service的名称获取场景名称对应的配置文件信息
-- Input
-- @param core 调用者自身self对象
-- Returns
-- @return
-----------------------------------------------------------------------------
function run(core)
    core.service_name = core.request.post_args.request.service
    ngx.say('common-trends-init-default-run() 赋予基本参数')
    core.service_conf = core.services[core.service_name]
    -- 将原始的请求数据传给子请求，用来记录日志的POST数据

end



