---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 3:01 PM
---

-----------------------------------------------------------------------------
-- 主feed流场景的策略处理模块
-----------------------------------------------------------------------------

local _M = {}


-----------------------------------------------------------------------------
-- 初始化方法
-- 会引用trends.strategy并加入元表，相当于继承该类
-- Input
-- @param core 调用者的自身对象self
-- Returns
-- @return 初始化后的对象
-----------------------------------------------------------------------------
function _M.new(self, core)
    local parent = require('trends.strategy')
    setmetatable(self, {__index=parent})
    local m = {core = core}
    return setmetatable(m, {__index = self})
end

-----------------------------------------------------------------------------
-- 执行策略方法
-- Input
-- @param core 调用者的自身对象self
-- Returns
-- @return
-----------------------------------------------------------------------------
function _M.run(self, core)
    if core.scheduler.modules then
        for _, mo in pairs(core.scheduler.modules) do
            ngx.say("执行mainfeed 策略")
        end
    end
end

return _M