---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 1:27 PM
---

-----------------------------------------------------------------------------
-- 初始化后面并行调用所需的各种参数
--
-----------------------------------------------------------------------------

module(..., package.seeall)

-----------------------------------------------------------------------------
-- 初始化方法
-- 默认调用./init/default.lua，该文件相当于该文件夹下其他类的父类
-- Input
-- @param core 传入调用者自身对象
-- Returns
-- @return 返回调用者自身对象，自身对象中此模块封装的各项数据
-----------------------------------------------------------------------------
function init(core)
    ngx.say('common-trends-init --初始化请求参数，此方法里面用到了self.request和self.services')
    local init_t = require('trends.init.default')
    init_t.run(core)
end