---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 1:31 PM
---

-----------------------------------------------------------------------------
-- 一些场景的策略处理模块
-- PM会对一些场景的数据配置提出一些要求，这些数据配置统一在这个模块里处理
--
-----------------------------------------------------------------------------

module(..., package.seeall)

-----------------------------------------------------------------------------
-- 初始化并执行场景下的策略配置
-- 如果该场景（如：queryfeed）下配置了策略，则初始化策略文件，并执行里面的策略方法
-- Input
-- @param core 调用者自身self
-- Returns
-- @return core 经过策略处理的自身self
-----------------------------------------------------------------------------
function init(core)

    local c = core.service_conf.strategy
    if c and c ~= '' then
        c='trends.'..c
        local t = require(c)
        local t_c = t:new(core)
        t_c:run(core)
    end
    ngx.say('加载运行策略')
    return core
end