---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xudong12.
--- DateTime: 2020/2/26 11:36 AM
---

-- 为方便测试，会将测试人员的id定向设置统一内容在redis里面
function handle_whitelist_test(uid,render_define_response)
    local redis_handle = require('service.redis')
    local cjson = require('cjson')
    if uid ==nil or render_define_response == nil then
        ngx.print('{"errno": 91, "error":"uid or render_define_response is empty"}')
    elseif render_define_response == '' then
        return redis_handle.del('testvalue_'..uid,"whitelist")
    else
        local status, redis_table_str = pcall(cjson.encode, {mobile={normal=render_define_response}})
        if status  then
            return redis_handle.set('testvalue_'..uid, redis_table_str, "whitelist")
        end


    end
end


ngx.req.read_body() --获取Post 数据
local post_params = ngx.req.get_post_args()

local status = handle_whitelist_test(post_params['uid'],post_params['render_define_response'])
if status then
    ngx.print('{"errno": 0, "error":"success"}')
else
    ngx.print('{"errno": 91, "error":"whitelist occur error"}')
end